# .github/workflows/deploy-pages.yml
name: Deploy lo8ding-web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build lo8ding-web
        run: yarn workspace lo8ding-web build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: lo8ding-web/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write # allow pushing to GH Pages
      id-token: write # required by the deploy action
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
